apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: smrutisw2001/todoimage:latest
        ports:
        - containerPort: 8000
~                           
